[program:registry]
command=/home/ubuntu/Northeastern-registry/.venv/bin/python registry.py
directory=/home/ubuntu/Northeastern-registry
user=ubuntu
autostart=true
autorestart=true
stderr_logfile=/var/log/registry.err.log
stdout_logfile=/var/log/registry.out.log
environment=
    MONGODB_URI="${MONGODB_URI}",
    MONGODB_DB="${MONGODB_DB}",
    PORT="6900",
    AUTH_NS_URL="http://${AGENTS_IP}:8300",
    ANS_APP="${ANS_APP}",
    ANS_TLD="${ANS_TLD}"

[program:agentfacts]
command=/home/ubuntu/Northeastern-registry/.venv/bin/python agentFactsServer.py
directory=/home/ubuntu/Northeastern-registry
user=ubuntu
autostart=true
autorestart=true
stderr_logfile=/var/log/agentfacts.err.log
stdout_logfile=/var/log/agentfacts.out.log
environment=
    ATLAS_URL="${MONGODB_URI}",
    PORT="8000"
