[program:mbta-auth-ns]
command=/opt/mbta-agents/venv/bin/python /opt/mbta-agents/ans/generic_auth_ns.py
directory=/opt/mbta-agents/ans
user=root
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/mbta-auth-ns.out.log
stderr_logfile=/var/log/mbta-auth-ns.err.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
environment=
    PYTHONPATH="/opt/mbta-agents",
    AGENT_HOST="${AGENTS_IP}",
    ANS_TLD="${ANS_TLD}",
    ANS_APP="${ANS_APP}",
    AUTH_NS_PORT="8300",
    ALERTS_SLIM_PORT="50051",
    PLANNER_SLIM_PORT="50052",
    STOPFINDER_SLIM_PORT="50053"
