[program:registry]
command=/home/ubuntu/Northeastern-registry/.venv/bin/python registry.py
directory=/home/ubuntu/Northeastern-registry
user=ubuntu
autostart=true
autorestart=true
stderr_logfile=/var/log/registry.err.log
stdout_logfile=/var/log/registry.out.log
environment=
    MONGODB_URI="mongodb+srv://nanda_admin:nanda_pass@cluster0.auzlobs.mongodb.net/?appName=Cluster0",
    MONGODB_DB="nanda_private_registry",
    PORT="6900",
    AUTH_NS_URL="http://96.126.111.107:8300",
    ANS_APP="mbta-transit-ci",
    ANS_TLD="agents.dataworksai.com"
